### ISSUE TITLE
Nodemon runs in endless loop

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/Office-Add-in-NodeJS-SSO#1]
I completed all the steps. But the `"tsc-w": "tsc -p tsconfig.json --watch"` command fails with -p flag is included. 
Once I get past that step removing -p flag, `npm run start` results in endless loop. 
![image](https://user-images.githubusercontent.com/8384457/27007492-18dedb96-4e0a-11e7-9dd8-f85dee1a4a01.png)

**Comment by Rick-Kirkham** [comment]
I cannot reproduce these errors.  What exactly is the failure when the tsc-w command executes?

**Comment by sumurthy** [comment]
Here is the error that I get when I do the npm run build. I have latest 8.* version of Node. 
Instead of doing all the TODO# fills, I started from completed folder and added the relevant tokens, etc.

![image](https://user-images.githubusercontent.com/8384457/27015620-492ed7f2-4ec7-11e7-9f93-832133f88b95.png)

**Comment by sumurthy** [comment]
Also, I hit several snags during npm install. I had to manually bring several modules such as nodemon.

**Comment by sumurthy** [comment]
I tested with the /Before folder and there it works okay. I'm able to start the server and load the add-in. I think there is some issue with the /Completed folder setup. You may want to re-create or copy over from Before to make it work.

**Comment by Rick-Kirkham** [comment]
I was using the Completed version when I tried to reproduce. I could not reproduce this error. That error normally means that the first character of the tsconfig.json file is not "{"  as it should be.
