### ISSUE TITLE
The scope is not valid

### ISSUE THREAD

**Issue by ardabeyazoglu** [OfficeDev/Office-Add-in-NodeJS-SSO#11]
Hi,

I followed the tutorial with the code in this repo to create a simple office365 word addin, and only changed the ids, secrets etc. however it doesn't work when it attempts to get an access token to retrive drive files. 

Here is the url (decoded) of the token request when i check in network:
`https://login.live.com/oauth20_authorize.srf?client_id=00000000481710A4&response_type=token&redirect_uri=https://p.sfx.ms/sa.html&state={"client_id":"00000000481710A4","network":"windows","display":"none","callback":"_hellojs_bd2pxupx","state":"","redirect_uri":"https://p.sfx.ms/sa.html","scope":"api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user"}&scope=api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user`

The response says The+provided+value+for+the+input+parameter+'scope'+is+not+valid.+The+scope+'api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user'+does+not+exist.`

The app id and resource url are already taken from application config page in developer portal, so they are correct. However, I dont know where the `client_id` in the url above is coming from.

**Comment by Rick-Kirkham** [comment]
We need more information to help you. What are the exact steps that lead up to the error. What is the error message?

**Comment by ardabeyazoglu** [comment]
The error message is included in the response: `The provided value for the input parameter 'scope' is not valid. The scope 'api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user' does not exist.`

I followed the steps as described in [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs).

**Comment by Rick-Kirkham** [comment]
The client_id is something internal when you are using a Microsoft Account, so that is expected. 
Are you logged into Office with more than one account? If so, try logging out of all accounts in Office. Closing all Office apps and then reopening and logging in with _only_ the Microsoft Account.
Does the **Scope** name in the application registration say 'api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user'?
What is the value you have for `<Resource>` inside the `<WebApplicationInfo>` in the manifest? It should _not_ have the "/access_as_user" on the end. 
What is the tool you are using to capture the request to login.live.com? Is it Fiddler? 
By "response" I assume that you mean the response to the request to login.live.com. Please confirm. 
What error, if any, is returned in the application from the call to `getAccessTokenAsync`? Is it 13001? 13002?, etc.

**Comment by ardabeyazoglu** [comment]
Hello,

1) I login with only one account in the same browser.
2) Manifest block is as follows: (also [here](https://prnt.sc/kajd6l))
        `<WebApplicationInfo>
	      <Id>dad7312f-6ccd-4026-8a80-86441223c790</Id>
	      <Resource>api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790</Resource>
	      <Scopes>
		<Scope>files.read.all</Scope>
		   <Scope>profile</Scope>
	      </Scopes>
	</WebApplicationInfo>`
3) I am checking request information in developer tools of the browser. Here is the url of login request:
`https://login.live.com/oauth20_authorize.srf?client_id=00000000481710A4&response_type=token&redirect_uri=https://p.sfx.ms/sa.html&state=		{"client_id":"00000000481710A4","network":"windows","display":"none","callback":"_hellojs_b5zd39bl","state":"","redirect_uri":"https://p.sfx.ms/sa.html","scope":"api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user"}&scope=api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user
`
4) This request gives 302 status code, and rediret url is as follows:
`https://p.sfx.ms/sa.html#error=invalid_scope&error_description=The+provided+value+for+the+input+parameter+'scope'+is+not+valid.+The+scope+'api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user'+does+not+exist.&state=%7b%22client_id%22:%2200000000481710A4%22%2c%22network%22:%22windows%22%2c%22display%22:%22none%22%2c%22callback%22:%22_hellojs_b5zd39bl%22%2c%22state%22:%22%22%2c%22redirect_uri%22:%22https://p.sfx.ms/sa.html%22%2c%22scope%22:%22api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user%22%7d`

5) Also, `getAccessTokenAsync` method response the following error after a second try:

Code: 13008
Message: The operation failed because this add-in is already requesting an access token.
name: Add-in is already requesting an access token.

**Comment by Rick-Kirkham** [comment]
Is an error returned from `getAccessTokenAsync` on the _first_ try? If not, what is returned as the `result `object to the callback on the first try?  If you put a `console.log("here")`; in the callback, does it run?

**Comment by ardabeyazoglu** [comment]
At first request it redirects to that error response i wrote above with the same error message “the scope is not valid”

**Comment by Rick-Kirkham** [comment]
@ardabeyazoglu 
I understand. But when `getAccessTokenAsync `completes, the callback that is passed to it runs. A `result` object is passed to that callback. The `result` object will contain a `result.status` of success or failure, and it will have a `result.error` property if the call of `getAccessTokenAsync` failed. It will have a result.value property if the call succeeded. I'm trying to understand from you if that callback ever runs (the _first_ time you call `getAccessTokenAsync`) and, if so, what properties the result object has. Please put these lines in the callback and tell me what they say the _first_ time you call `getAccessTokenAsync`:

```
console.log(result.status);
console.log(result.error);
console.log(result.value);
 
```

**Comment by ardabeyazoglu** [comment]
This code does not log anything. Callback is not executed.

```javascript
Office.context.auth.getAccessTokenAsync({forceConsent: false},
            function (result) {
                console.log(result.status);
                console.log(result.error);
                console.log(result.value);
            });
```

**Comment by Rick-Kirkham** [comment]
OK. An internal developer is reporting a problem with a "scope" error (on Windows Office, not Office Online). We are working on it. I will report back anything useful.

**Comment by ardabeyazoglu** [comment]
Thanks. But i am using online office and got this problem there.

**Comment by Rick-Kirkham** [comment]
I understand. We think a bug in Microsoft Account identity system might be the cause of the error on both Windows Office and Office Online. It might be that the app registration is not getting saved to MS identity.

**Comment by ardabeyazoglu** [comment]
I understand and it might be noteworthy to mention that I am testing it without installing from market. I upload the manifest xml to try. Everything else works except `getAccessTokenAsync`.

**Comment by Rick-Kirkham** [comment]
@ardabeyazoglu The Microsoft Account identity team thinks that they might have it fixed. They've asked that you try again.

**Comment by ardabeyazoglu** [comment]
Thanks! I ll try it asap and let you know the result.

**Comment by ardabeyazoglu** [comment]
Hello again, sorry for late answer. We tried again but didnt work. everything was the same.

**Comment by Rick-Kirkham** [comment]
The product team asks you to double check that in your app configuration in apps.dev.office.com, in the WebAPI section, the app’s URI is api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790 and he added scope: api://localhost:3000/dad7312f-6ccd-4026-8a80-86441223c790/access_as_user.

If the configuration is OK, then you are hitting a bug where the scope permissions for Microsoft Accounts is not being propagated to all the Azure servers where it needs to be. All we can do is wait for this to be fixed.

**Comment by ardabeyazoglu** [comment]
Thanks, this was the issue. I created the web api section from scratch again. The scope automatically includes localhost:3000 but "Application ID Uri" does not. After i manually change it and add localhost:3000, it started to work.
