### ISSUE TITLE
Does SSO work on Desktop clients?

### ISSUE THREAD

**Issue by elrapha** [OfficeDev/Office-Add-in-NodeJS-SSO#19]
Is this supposed to work on desktop clients? I read that getAccessToken is in preview mode for desktop clients. Am I missing some updates to the api? I am building for Outlook

**Comment by Rick-Kirkham** [comment]
Yes. It is available (as a preview) on desktop clients, including Outlook. You have to be in the Office Insiders program, however. See here https://docs.microsoft.com/en-us/javascript/office/requirement-sets/identity-api-requirement-sets?view=office-js

(There is a mistake in that table, however, the two places where you see "Available" should say "Preview" (with no asterisk). The API is preview on all hosts/platforms. I'll get that fixed. )
