### ISSUE TITLE
Add-in is not sideloading in outlook when uploaded as custom add-in

### ISSUE THREAD

**Issue by Devang142** [OfficeDev/Office-Add-in-NodeJS-SSO#20]
I followed all the steps specified [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs) to test SSO for outlook in local. I uploaded manifest file(attached below) as custom add-in, but when I close the store popup, it not showing up beside store icon.

Current outlook version is: **Outlook 2016 version 1803 (16.0.9126.2295)**

And here is manifest file:
[manifest.txt](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/files/2500659/manifest.txt)

I am not sure what I am doing wrong, please help me with this.

**Comment by Rick-Kirkham** [comment]
@Devang142 Thanks for your interest in the preview of Single Sigh-on. The issues for this repo are intended for reporting problems with the sample "as is". Now, that you have moved on to creating your own Outlook add-in that uses SSO, you should raise difficulties on StackOverflow. That way the whole community will benefit from the answers that you get. Be sure to tag your StackOverflow question with `office-js` and `oulook-addin`.
