### ISSUE TITLE
Token version mis match with new App Registration (Preview)

### ISSUE THREAD

**Issue by venkatkonjeti** [OfficeDev/Office-Add-in-NodeJS-SSO#21]
For this sample I had registered my App in **apps.dev.microsoft.com**, the **getAccessTokenAsync()** method returns v2.0 token. Using this token I was able to get graph v2.0 token everything works fine.

When I registered the app under the **Azure Portal** -> **App Registration (Preview),** the **getAccessTokenAsync()** method returns the v1.0 token. So, JWT token validation fails and I am unable to get the graph token.

I would like to know is this going to be v1.0 token in future or is this bug in preview?

**Comment by Rick-Kirkham** [comment]
@venkatkonjeti 
This is by design. You must register the app in apps.dev.microsoft.com to use the SSO preview.

**Comment by venkatkonjeti** [comment]
The purpose of new App Registration under Azure Portal is to replace the apps.dev.microsoft.com as per Azure team.

In this case it should work as before if I am right.

Can you please clarify.

**Comment by Rick-Kirkham** [comment]
Please clarify "as per Azure team". Where did you get this information?

**Comment by venkatkonjeti** [comment]
This was announced at [ignite session](https://www.youtube.com/watch?v=pB5K1qIj-oQ) 14:13. And I can see anything I was registered under apps.dev.microsoft.com into the Azure Portal -> App Registration (Preview).

**Comment by Rick-Kirkham** [comment]
@venkatkonjeti 
I'll ask the developers. This is news to me.

**Comment by venkatkonjeti** [comment]
Thanks for taking care. Can you please move to open status. If anybody knows about this they will also join the discussion.

**Comment by Rick-Kirkham** [comment]
@venkatkonjeti 
Actually, you should raise this question on StackOverflow for maximum visibility. (Be sure to tag it `office-js`.)The issues for this repo are only for problems with this sample "as it is". As you'll see in the Readme, the sample is meant to be used in conjunction with a walkthrough in our documentation. That walkthrough specifies that apps.dev.microsoft.com be used for registration. I gather from your original question that it works when registered that way, so this isn't really an issue for this sample.

**Comment by venkatkonjeti** [comment]
Okay. Make sense. Thanks again.
