### ISSUE TITLE
Office.context.auth sometimes undefined

### ISSUE THREAD

**Issue by isawek** [OfficeDev/Office-Add-in-NodeJS-SSO#25]
Hi,

i wrote an Office-Add-in for Word and use SSO. Sometimes my api calls work fine but most time the Office.context.auth is undefined so i can´t call getAccessTokenAsync.

tried to call it later with a btn click or with Office.onReady().then(() => {...}) but it doesn´t help.

I use Office 365 ProPlus.
Word Version is 1812

**Comment by niteshgolchha85** [comment]
Are you referencing the beta version of office.js in your project? Please note that SSO is in preview and should not be used in production.

**Comment by cbuettemeier** [comment]
Yes, and to be honest, this becomes more and more annoying. How long is this already in preview? How are we developers for Office solutions supposed to fiddle around with a beta preview and some vague intimations regarding the future of this? In the meantime I have spend a good deal of time in learning the specifics of SSO in Office Addins. But nothing really happens to leverage this to a final state. Sure, I can fall back to ADAL every time, but this is clearly not how customers are expecting their user experience nowadays. From my point of view nearly everything needed is there - why is this such an endless process with official support? 

(yes, obviously not a question for an issue in this GitHub project, but this is rather frustrating. Sorry for that.)

**Comment by niteshgolchha85** [comment]
I can understand your frustration, given the amount of time its taking to go GA, but we have been hitting some really big roadblocks. The major issue is around consent replication and there are some other minor issues as well. That said, we are working towards a solution and I am confident that you will hear back from us real soon.

Coming to the actual issue, I checked with internal engineers and we suspect that Office.js might not be loaded successfully so can you help answer below qs:
1. Are you invoking Office.context.auth after DOM has loaded, as per the given documentation?
2. Are other APIs working? Or is it only auth that is undefined?

**Comment by isawek** [comment]
Sorry for the late response but i was on vacation.

1. We first call it in the componentDidMount react method.
2. Our own APIs are working. I inserted a button that inserts some text to the word document [like here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visual-studio) and we have the same problem (they work and don´t work together).

following error is returned when i call the word api and it doesn´t work:
{
	"description":"Objekt erwartet",
	"number":-2146823281,"
	stack":"TypeError: Objekt erwartet
		at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:3484:7)
		at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:13579:5)
		at lib$es6$promise$$internal$$initializePromise (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:9261:8)
		at lib$es6$promise$promise$$Promise (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:9416:8)
		at OfficeJsRequestExecutor.prototype.executeAsync (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:13578:4)
		at ClientRequestContext.prototype.syncPrivate (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:12401:4)
		at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.debug.js:12367:65)
		at run (eval code:75:13)
		at Anonymous function (eval code:92:30)
		at flush (eval code:18:9)"
}

**Comment by isawek** [comment]
Ok, i found the problem. in the index.html was a second script tag with the office.js as src.

Thank you for your help.
