### ISSUE TITLE
getAccessTokenAsync give me 5001 error

### ISSUE THREAD

**Issue by dianibar** [OfficeDev/Office-Add-in-NodeJS-SSO#3]
Hi,
I follow all the steps given in the example and then when I try to run the add-in in power-point on-line Build:16.0.8812.5630. I got the next error:

![error-2017-11-15 10-12-01](https://user-images.githubusercontent.com/4245701/32810115-afbfdf88-c9ed-11e7-84b9-65118b98771d.png)

Code:5001
Message: An internal error has occurred
name: Internal Error

Any ideas what this is happening? Can I use the SSO in this build version?

Thanks for your help.

**Comment by Rick-Kirkham** [comment]
Please install the Fiddler tool (or Charles tool) and see what the network call looks like when `getAccessTokenAsync` runs. There are links to the tools in this article: [Troubleshoot SSO in Office Add-ins](https://dev.office.com/docs/add-ins/develop/troubleshoot-sso-in-office-add-ins)

**Comment by Rick-Kirkham** [comment]
Closing because haven't heard back from customer.
