### ISSUE TITLE
Can we have a proper readme.md file to follow steps to execute the solution

### ISSUE THREAD

**Issue by aagamdoshi** [OfficeDev/Office-Add-in-NodeJS-SSO#45]
As of now the solution seems pretty difficult whats the start point and all the stuffs for a beginner for Office.js , some steps to run the solution , would be helpful

**Comment by Rick-Kirkham** [comment]
If you are a beginner with Office.js, you should probably use the AutoSetup version of the sample which has its own readme here: [SSOAutoSetup Readme](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/tree/master/SSOAutoSetup).

But auth and SSO are difficult subjects and this is a complex sample. If you really are a beginner you should try to get to an "intermediate" stage before you take on auth/SSO. I recommend that you start here: [Start Here! A guide for beginners making Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-beginner).
