### ISSUE TITLE
Can Passport now be included in this sample now issues with dynamic keys?

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/Office-Add-in-NodeJS-SSO#5]
Now these issues are resolved,

Looking at 
https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO/blob/master/Completed/src/auth.ts 

 * (https://github.com/themikenicholson/passport-jwt/pull/108)
 * (https://github.com/themikenicholson/passport-jwt/issues/94)

Can we please see this sample using the Passport implementation? Now that dynamic keys are useable?

Cheers

Nigel D

**Comment by Rick-Kirkham** [comment]
@nigel-dewar 
I'm afraid that changing the sample to use passport is very low priority. If someone in the community wants to do it, we could consider a Pull Request, or perhaps adding passport version as a second version. In the meantime, I plan to remove the mention of passport from the file. Realistically, there's very little chance we'll ever do this.

**Comment by nigel-dewar** [comment]
NP Rick , makes sense.

I'll sort it and submit a PR. I'll even through in some socket.io goodness for freeeeeee.

Love your work by the way, really good samples, good quality stuff that I reference all the time.

Cheers mate.

Nigel
