### ISSUE TITLE
Deploying solution started from this example

### ISSUE THREAD

**Issue by LiamSolDev** [OfficeDev/Office-Add-in-NodeJS-SSO#61]
Hi,
I have been working on a solution using the code provided here as a starting point.

I went to turn the solution into a production build by following the steps provided here:
https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code

but hit issues when trying to run "npm start build", receiving the message:
![image](https://user-images.githubusercontent.com/44843976/114204815-88b69580-9951-11eb-9ecc-351398432981.png)

Have I missed something that has lead to no build being available or do you have a fix?

**Comment by Rick-Kirkham** [comment]
That article is about deploying an add-in created with the Yo Office tool. That tool creates a `build` script in the projects that it creates. But there is no such script in this sample. I believe that most of the steps in that article will work for this sample, with these exceptions:
In step 6, do not change the name of `index` to `taskpane`. 
For step 9, you will have to manually create a dist folder and move the files that go on the Azure website into it. This should include the app.js file and the folders Public, Routes, and View.
You can then continue with steps 10 and 11.

If this doesn't work, then you'll have to deploy the add-in without tools. Read Azure help for how to deploy a NodeJS/express web app to Azure. Then be sure to change the `localhost:nnnnn` domain in the manifest to the domain of the new Azure site.

**Comment by Rick-Kirkham** [comment]
@davidchesnut Assigning to you for long term handling.

**Comment by LiamSolDev** [comment]
Hi Rick,

Thank you for you help.

I followed the steps provided but still encountering issues- could this be caused by the solutions use of pug files rather than straight html?
the paths provided in the manifest (after changing to the azure address) point to: https://XXX.z22.web.core.windows.net/home/index however there is no home folder and the file called index is index.pug which I believe will not be immediately resolved as a html page.
I will attempt to swap out the root address to the index and make an index.html rather than .pug and see if this allows me to access the page

**Comment by LiamSolDev** [comment]
Hi Rick,

Another message if you don't mind,
Still not been able to get the app visible in the taskpane after swapping out the index (can only view the index.html page directly in the browser). While struggling with this I have moved onto the Azure side, and added a new address to the redirect urls: https://XXX.z22.web.core.windows.net/public/dialog.html

but I do not know if I need to change the url api://localhost:44355/b42bd68b-576e-42a6-9251-6d75b026f456 to point at the new domain, and if it does need changed do I just swap out the localhost:44355 for xxx.web.core.windows.net/

**Comment by Rick-Kirkham** [comment]
Yes. You have to change the localhost:4355 domain to the new domain everywhere in the manifest and in the Azure portal where the add-in is registered. 

Can you give a screen shot of your /dist folder, so I can see how its structured?

**Comment by LiamSolDev** [comment]
Hi Rick,

Thanks for the reply- I will change that now.
Please see the structure of my dist folder and a copy of my manifest file :)

Dist folder Root
![distRoot](https://user-images.githubusercontent.com/44843976/114519449-55695480-9c38-11eb-93a4-88e580b27203.PNG)

Home folder
![home](https://user-images.githubusercontent.com/44843976/114519499-61551680-9c38-11eb-9e16-3ebbb6e0b4a7.PNG)

Public folder
![publci](https://user-images.githubusercontent.com/44843976/114519533-6ade7e80-9c38-11eb-924a-a6561c0091ac.PNG)

Public -> Javascript folder
![publicJavascript](https://user-images.githubusercontent.com/44843976/114519565-716cf600-9c38-11eb-84b6-126c4c467cce.PNG)

Routes folder
![routes](https://user-images.githubusercontent.com/44843976/114519610-7cc02180-9c38-11eb-97a0-12062c3cbcae.PNG)

Views folder (no longer believe this is being used? since I created the new index file, unless this is used elsewhere)
![views](https://user-images.githubusercontent.com/44843976/114519642-86498980-9c38-11eb-803c-980c66a0d149.PNG)

**Comment by LiamSolDev** [comment]
Hi Rick,

The app is now loading from the index.html page, which is good. Looks to have been maybe some sort of caching issue.

However, I have attempted to change the Application ID url to the Azure url (xxx.web.core.windows.net/) but get the following error:
![image](https://user-images.githubusercontent.com/44843976/114554890-16022e80-9c5f-11eb-8a22-aea7eff8e443.png)

Have you encountered this before? I couldn't find anyone else having the same issue through searching.

**Comment by davidchesnut** [comment]
Hi @LiamSolDev,

The article [Publish an add-in developed with Visual Studio Code](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code) shows how to deploy to a static website. Unfortunately a static website will not work with SSO because you must have a web server to respond to API requests from the add-in. So you'll need to set up an API server of some sort on Azure to handle the API calls from the add-in.

Cheers,
David

**Comment by LiamSolDev** [comment]
Hi David,

Thanks for the response.
Do you have any advice or are you aware of any tutorials that show how to go about doing this?

I tried deploying to an azure webapp (azure appservice) but did not have any success, I cannot seem to navigate to any page and see the following errors in the Diagnose and Solve Problems:
![image](https://user-images.githubusercontent.com/44843976/115016729-5fe05400-9ead-11eb-9661-38d0ad27d2aa.png)

**Comment by davidchesnut** [comment]
Hi @LiamSolDev,

Yeah, you'll need to modify the sample to get it to deploy correctly. I got this working, so I'll share my notes as follows:
- For the app service, I used the Windows OS (not linux) and ran the node 12 lts runtime stack.
- The /bin/www file attempts to use office-addin-dev-certs, but this won't work on Azure. Remove any code attempting to use office-addin-dev-certs, and modify the create server to `https.createServer(app).listen(port, () => console.log(`Server running on ${port}`));`
- Update your manifest xml to refer the your Azure endpoint (not localhost).
- Add a web redirect URI for your azure endpoint. For example, in fallbackAuthDialog.js, line 42 should read similar to this:   `redirectURI: "https://myAppService.azurewebsites.net/dialog.html",`
- Also add that redirect URI to your app registration in the Azure portal.
- Be sure the .ENV file has the correct client id and client secret.
- Modify the package.json to just start the node server with `"start": "node ./bin/www"`

Hope this helps,
David

**Comment by davidchesnut** [comment]
Hi @LiamSolDev,

One more thing to mention is that while storing the client secret in the .ENV file will get this sample working, it's not a secure method of storing the secret. You should take a look at [Quickstart: Azure Key Vault secret client library for JavaScript (version 4)](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-node).

Cheers,
David

**Comment by LiamSolDev** [comment]
Hi David,

Thanks for you support :)

We were able to get the sample deployed.
I will look into the secure keystore at my next possible opportunity, thank you and Rick for your assistance.

Kind Regards,
Liam

**Comment by LiamSolDev** [comment]
Update- Manged to fix ourselves, issues with configuration not being multi tenant :) 
If you do know why these solutions need to be multi-tennant to work even when the users are on the same o365 tennant  I would be intrested to know.

Thank you :) Closing again.
