### ISSUE TITLE
Error 13006 : An unexpected error occurred in the client.

### ISSUE THREAD

**Issue by blandine** [OfficeDev/Office-Add-in-NodeJS-SSO#8]
Hi,
Thank you for this sample :)
I launched the completed version but I have an error in the console when trying to get the OneDrive files : 
` Error 13006 : An unexpected error occurred in the client. 
Error occurred in the authentication request from Office.`
I tried on Windows Excel and online Excel.
I changed nothing except the application id in the manifest.

Thank you for your help

**Comment by Rick-Kirkham** [comment]
The only information I have for 13006 is in this article: [Troubleshoot SSO](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins). Did you make the needed changes to the web.config?

**Comment by blandine** [comment]
Thanks for your reply !
I'm in a full nodejs environment : I run the sample with npm run start (as specified in the package.json file). 
No IIS, no VS so I don't have any web.config.
What did you mean exactly by the "needed changes in web.config"? If the server needs to be customized, I guess we can do the same with Node.
However, I don't know where to start. The error is a bit unclear ...
Would it be possible to setup a running demo with this sample so we can compare?

**Comment by Rick-Kirkham** [comment]
@blandine My bad. We have an ASP.NET sample too and I got them mixed up. This sample, of course, has no web.config. What I should have asked was whether you'd carried out the steps in https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs#configure-the-add-in
